name: app deployment

on:
  push:
    branches: [ main]
  pull_request:
    branches: [ main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install NodeJS
      uses: actions/setup-node@v2-beta
      with:
        node-version: 12
    
    - uses: borales/actions-yarn@v2.0.0
      with:
        cmd: install # will run `yarn install` command
        
    - name: Build React App
      run: yarn build
      
    - name: Install Surge
      run: npm install --global surge

    - name: Deploy to Surge
      run: surge ./build https://project-5-by-gopal.surge.sh --token ${{ secrets.SURGE_TOKEN }}
